desktop works

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -84,7 +84,7 @@ jobs:
           
               # Check if the actual count meets or exceeds the minimum required count
               if [ "$((actual_count - 1))" -eq "$exact_count" ]; then
-                echo "Directory $dir_path has the exact required count ($actual_count items):"
+                echo "Directory $dir_path has the exact required count ($((actual_count - 1)) items):"
                 # List directory contents based on the OS
                 if [[ ${{ matrix.os }} == "windows-latest" ]]; then
                   dir "$dir_path"
@@ -92,7 +92,7 @@ jobs:
                   ls -la "$dir_path"
                 fi
               else
-                echo "Directory $dir_path does not meet the exact required count. Expected $exact_count, but found $actual_count." && exit 1
+                echo "Directory $dir_path does not meet the exact required count. Expected $exact_count, but found $((actual_count - 1))." && exit 1
               fi
             else
               echo "Directory does not exist: $dir_path" && exit 1
